#!/bin/sh
set -e
	update-alternatives --install /sbin/klogd klogd /usr/lib/busybox/sbin/klogd 50
	update-alternatives --install /sbin/syslogd syslogd /usr/lib/busybox/sbin/syslogd 50
OPTS=""

if [ -n "$D" ]; then
    OPTS="--root=$D"
fi

if type systemctl >/dev/null 2>/dev/null; then
	if [ -z "$D" ]; then
		systemctl daemon-reload
	fi

	systemctl $OPTS enable busybox-syslog.service

	if [ -z "$D" -a "enable" = "enable" ]; then
		systemctl --no-block restart busybox-syslog.service
	fi
fi
