set -e
    if false; then
        if false; then
             update-alternatives --install /etc/init.d/firmware-links.sh firmware-links.sh firmware-links.sh 60
             [ -n "$D" ] && OPT="-r $D" || OPT="-s"
             # remove all rc.d-links potentially created from alternatives
             update-rc.d $OPT -f firmware-links.sh remove
             update-rc.d $OPT firmware-links.sh multiuser
        fi
    fi
