#!/bin/sh
set -e
OPTS=""

if [ -n "$D" ]; then
    OPTS="--root=$D"
fi

if type systemctl >/dev/null 2>/dev/null; then
	if [ -z "$D" ]; then
		systemctl daemon-reload
	fi

	systemctl $OPTS enable firmware.mount persist.mount cache.mount data.mount systemrw.mount

	if [ -z "$D" -a "enable" = "enable" ]; then
		systemctl --no-block restart firmware.mount persist.mount cache.mount data.mount systemrw.mount
	fi
fi
