#!/bin/sh
#==============================================================================
# FILE: ipa_fws_le
#
# DESCRIPTION:
# Indicate to IPA driver that FWs are available from user space for fetching
# and loading
#
# Copyright (c) 2017, 2020, Qualcomm Technologies, Inc.
# All Rights Reserved.
# Confidential and Proprietary - Qualcomm Technologies, Inc.
#==============================================================================
# Look for ipa_config.txt file and cat it's content to /dev/ipa before ipa is ready.
# A write of 1 or MHI to /dev/ipa will indicate that user space is available and the
# FWs can be fetched.
# add support to write DBS to allow wlan-driver connect 2 tx pipes
FILE=/etc/data/ipa_config.txt
if [ -f $FILE ]; then
  echo $(cat $FILE) > /dev/ipa
fi
# This is to enable WLAN 2 pipe solution and replace DBS with mhi if
# mhi usecases is excersized
echo DBS > /dev/ipa
