#!/bin/sh
# Copyright (c) 2020 Qualcomm Technologies, Inc.
# All Rights Reserved.
# Confidential and Proprietary - Qualcomm Technologies, Inc.
#
# Copyright (c) 2019, The Linux Foundation. All rights reserved

# WLAN module init.d script

export MODULE_BASE=/usr/lib/modules/`uname -r`/
set -e

export MAG=$(echo `cat /sys/firmware/devicetree/base/model` | grep MAG)
if [[ "$MAG" != "" ]]
then
    export WLAN_KO=$MODULE_BASE/extra/wlan-mag.ko
else
    export WLAN_KO=$MODULE_BASE/extra/wlan.ko
fi

case "$1" in
  start)
        echo -n "Starting/Loading WLAN module: " > /dev/kmsg

        echo "wlan:start/load" > /dev/kmsg

		code=`cat /tmp/wifi/hostapd.conf | grep "country_code" | awk -F= '{print $2}'`
		wififem=`nvram get wifi_fem 2>&1`
		if( [  -z "$wififem" ] )
		then
			wififem=0
		fi		
	max_sta=`nvram get wifi_max_sta 2>&1`
	if [ ! $max_sta ] || [ $max_sta -le 0 ] || [ $max_sta -gt 32 ]; then
		max_sta=32
	fi
       
        insmod $WLAN_KO country_code=$code fem_type=$wififem gSoftApMaxPeers=$max_sta

        echo "done loading WLAN module" > /dev/kmsg
        ;;
  stop)
        echo -n "Unloading wlan.ko " > /dev/kmsg
        rmmod $WLAN_KO
        echo "done unloading WLAN module" > /dev/kmsg
        ;;
  restart)
        $0 stop
        $0 start
        ;;
  *)
        echo "Usage { start | stop | restart}" >&2
        exit 1
        ;;
esac

exit 0
