#! /bin/sh
#
#Copyright (c) 2017, 2020 Qualcomm Technologies, Inc.
#All Rights Reserved.
#Confidential and Proprietary - Qualcomm Technologies, Inc.
#
# port_bridge   init.d script to start the Data Software's port_bridge daemon

set -e

case "$1" in
  start)
        echo -n "Starting port_bridge: "
        start-stop-daemon -S -b -a /usr/bin/port_bridge at_mdm0 at_usb0
        start-stop-daemon -S -b -p /dev/null -x /usr/bin/port_bridge smd8 at_usb2
        echo "done"
        ;;
  stop)
        echo -n "Stopping port_bridge: "
        start-stop-daemon -K -n port_bridge
        echo "done"
        ;;
  restart)
        $0 stop
        $0 start
        ;;
  *)
        echo "Usage port_bridge { start | stop | restart}" >&2
        exit 1
        ;;
esac

exit 0

